Update.
2003-07-14  Ulrich Drepper  <drepper@redhat.com>

	* sysdeps/pthread/configure.in: Require CFI directives also for
	ppc and s390.

diff --git a/nptl/sysdeps/pthread/configure b/nptl/sysdeps/pthread/configure
--- a/nptl/sysdeps/pthread/configure
+++ b/nptl/sysdeps/pthread/configure
@@ -6,12 +6,14 @@ echo "$as_me: error: compiler support for __thread is required" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-if test "x$libc_cv_asm_cfi_directives" != xyes; then
-    if test "x$base_machine" = xi386 || test "x$base_machine" = "xx86_86"; then
-    { { echo "$as_me:$LINENO: error: CFI directive support in assembler is required" >&5
+if test "sx$libc_cv_asm_cfi_directives" != xyes; then
+    case "$base_machine" in
+    i386 | x86_64 | powerpc | s390)
+      { { echo "$as_me:$LINENO: error: CFI directive support in assembler is required" >&5
 echo "$as_me: error: CFI directive support in assembler is required" >&2;}
-   { (exit 1); exit 1; }; }
-  fi
+   { (exit 1); exit 1; }; } ;;
+    *) ;;
+  esac
 fi
 
 
