Update.
2003-07-03  Ulrich Drepper  <drepper@redhat.com>

	* configure.in: Also check for .cfi_rel_offset pseudo-op.

diff --git a/nptl/sysdeps/pthread/configure b/nptl/sysdeps/pthread/configure
--- a/nptl/sysdeps/pthread/configure
+++ b/nptl/sysdeps/pthread/configure
@@ -6,6 +6,12 @@ echo "$as_me: error: compiler support for __thread is required" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
+if test "x$libc_cv_asm_cfi_directives" != xyes; then
+  { { echo "$as_me:$LINENO: error: CFI directive support in assembler is required" >&5
+echo "$as_me: error: CFI directive support in assembler is required" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 
 echo "$as_me:$LINENO: checking for forced unwind support" >&5
 echo $ECHO_N "checking for forced unwind support... $ECHO_C" >&6
@@ -14,11 +20,7 @@ if test "${libc_cv_forced_unwind+set}" = set; then
 else
   cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
+#include "confdefs.h"
 #include <unwind.h>
 int
 main ()
@@ -46,8 +48,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   libc_cv_forced_unwind=yes
 else
   echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
+cat conftest.$ac_ext >&5
 libc_cv_forced_unwind=no
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
@@ -68,11 +69,7 @@ if test "${libc_cv_c_cleanup+set}" = set; then
 else
     cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
+#include "confdefs.h"
 
 #include <stdio.h>
 void cl (void *a) { }
@@ -102,8 +99,7 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   libc_cv_c_cleanup=yes
 else
   echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
+cat conftest.$ac_ext >&5
 libc_cv_c_cleanup=no
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
