Update.
1998-12-02  Ulrich Drepper  <drepper@cygnus.com>

	* elf/elf.h: Add R_MIPS_JALR and adjust R_MIPS_NUM appropriately.

1998-12-02  Andreas Jaeger  <aj@arthur.rhein-neckar.de>

	* inet/Versions: Remove inet6_isipv4mapped.

1998-12-02  Philip Blundell  <pb@nexus.co.uk>

	* inet/in6_addr.c (inet6_isipv4mapped): Obsolete, deleted.

1998-11-30  Andreas Schwab  <schwab@issan.cs.uni-dortmund.de>

	* manual/time.texi (Formatting Date and Time): Fix typo.

1998-11-30  Andreas Schwab  <schwab@issan.cs.uni-dortmund.de>

	* sysdeps/unix/sysv/linux/configure.in: Only check for symlinks
	when configuring natively.  Use autoconf macros instead of rolling
	our own.  Handle defaulted prefix.

diff --git a/sysdeps/unix/sysv/linux/configure b/sysdeps/unix/sysv/linux/configure
--- a/sysdeps/unix/sysv/linux/configure
+++ b/sysdeps/unix/sysv/linux/configure
@@ -117,25 +117,31 @@ case "$machine" in
 esac
 
 
-# If $prefix/include/{net,scsi} are symlinks, make install will
-# clobber what they're linked to (probably a kernel tree).
-# test -L ought to work on all Linux boxes.
-echo $ac_n "checking for symlinks in ${prefix}/include...$ac_c"
-if test -L ${prefix}/include/net
-then message="   ${prefix}/include/net is a symlink"
-fi
-if test -L ${prefix}/include/scsi
-then message="$message
-   ${prefix}/include/scsi is a symlink"
-fi
-if test -n "$message"; then
-echo "
-*** error:
+if test $host = $build; then
+  # If $prefix/include/{net,scsi} are symlinks, make install will
+  # clobber what they're linked to (probably a kernel tree).
+  # test -L ought to work on all Linux boxes.
+  if test "x$prefix" != xNONE; then
+    ac_prefix=$prefix
+  else
+    ac_prefix=$ac_default_prefix
+  fi
+  echo $ac_n "checking for symlinks in ${ac_prefix}/include""... $ac_c" 1>&6
+echo "configure:131: checking for symlinks in ${ac_prefix}/include" >&5
+  if test -L ${ac_prefix}/include/net; then
+    message="   ${ac_prefix}/include/net is a symlink"
+  fi
+  if test -L ${ac_prefix}/include/scsi; then
+    message="$message
+   ${ac_prefix}/include/scsi is a symlink"
+  fi
+  if test -n "$message"; then
+    { echo "configure: error: 
 $message
 \`make install' will destroy the target of the link(s).
 Delete the links and re-run configure, or better still, move the entire
-${prefix}/include directory out of the way."
-exit 1
-else
-echo " ok"
+${ac_prefix}/include directory out of the way." 1>&2; exit 1; }
+  else
+    echo "$ac_t""ok" 1>&6
+  fi
 fi
