Regenerated: autoconf  sysdeps/mach/hurd/configure.in

diff --git a/sysdeps/mach/hurd/configure b/sysdeps/mach/hurd/configure
--- a/sysdeps/mach/hurd/configure
+++ b/sysdeps/mach/hurd/configure
@@ -5,3 +5,7 @@ DEFINES="$DEFINES -D_LIBC_REENTRANT"
 # Don't bother trying to generate any glue code to be compatible with the
 # existing system library, because we are the only system library.
 inhibit_glue=yes
+
+if test "x$prefix" != x; then
+  echo "configure: warning: --prefix= (empty) is required for GNU/Hurd to work normally" 1>&2
+fi
